<?php
// Generated by Zend Framework 2
return array(
    'Forum\Module'                     => __DIR__ . '/Module.php',
    'Forum\Controller\IndexController' => __DIR__ . '/src/Forum/Controller/IndexController.php',
    'Forum\Model\User'                 => __DIR__ . '/src/Forum/Model/User.php',
);